language: node_js
node_js:
  - 10
  - 12

script:
  - npm run build

after_script:
  - ./node_modules/.bin/jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
